apiVersion: v1
kind: Service
metadata:
  name: sshjump
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sshjump
  ports:
    - protocol: TCP
      name: "ssh"
      port: 2222
      targetPort: 2222

