
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshjump-reader-sa
  namespace: sshjump
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshjump-reader-role
  namespace: sshjump
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sshjump-reader-rb
  namespace: sshjump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sshjump-reader-role
subjects:
- kind: ServiceAccount
  name: sshjump-reader-sa
  namespace: sshjump
